name: Sync to GitLab

on:
  push

jobs:
  sync:
    runs-on: [self-hosted, image:debian:stable-slim]
    steps:
      - name: Sync to GitLab
        uses: kujov/gitlab-sync@2.2.0
        with:
          gitlab_url: https://gitlab.com/Maingron/Maingron
          username: Maingron
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
